import { 
  List, 
  Database, 
  Code, 
  Image as ImageIcon, 
  Video, 
  Activity, 
  Globe, 
  ShoppingBag, 
  FileCode, 
  Zap, 
  BarChart3, 
  Settings, 
  Key, 
  Shield, 
  Terminal, 
  Check, 
  X, 
  Trash2, 
  Plus, 
  Minus, 
  Sun, 
  Moon, 
  Info, 
  Rocket, 
  Copy, 
  Download, 
  Upload, 
  Heart, 
  Clock, 
  RefreshCw, 
  Eye, 
  AlertTriangle, 
  Loader2, 
  ChevronLeft, 
  ChevronRight, 
  Menu, 
  Star,
  Bolt,
  Type,
  PieChart,
  MousePointer2,
  Server,
  HelpCircle,
  BookOpen,
  Search,
  ChevronDown
} from 'lucide-react';
import React from 'react';

export const Icons: Record<string, React.ReactNode> = {
  list: <List size="100%" />,
  cache: <Database size="100%" />,
  code: <Code size="100%" />,
  image: <ImageIcon size="100%" />,
  media: <Video size="100%" />,
  vitals: <Activity size="100%" />,
  db: <Database size="100%" />,
  cdn: <Globe size="100%" />,
  shop: <ShoppingBag size="100%" />,
  script: <FileCode size="100%" />,
  preload: <Zap size="100%" />,
  chart: <BarChart3 size="100%" />,
  settings: <Settings size="100%" />,
  key: <Key size="100%" />,
  shield: <Shield size="100%" />,
  dev: <Terminal size="100%" />,
  check: <Check size="100%" />,
  x: <X size="100%" />,
  trash: <Trash2 size="100%" />,
  plus: <Plus size="100%" />,
  minus: <Minus size="100%" />,
  sun: <Sun size="100%" />,
  moon: <Moon size="100%" />,
  info: <Info size="100%" />,
  rocket: <Rocket size="100%" />,
  zap: <Zap size="100%" />,
  copy: <Copy size="100%" />,
  download: <Download size="100%" />,
  upload: <Upload size="100%" />,
  heart: <Heart size="100%" />,
  clock: <Clock size="100%" />,
  refresh: <RefreshCw size="100%" />,
  globe: <Globe size="100%" />,
  eye: <Eye size="100%" />,
  warning: <AlertTriangle size="100%" />,
  spinner: <Loader2 size="100%" className="animate-spin" />,
  collapse: <ChevronLeft size="100%" />,
  expand: <ChevronRight size="100%" />,
  menu: <Menu size="100%" />,
  star: <Star size="100%" />,
  activity: <Activity size="100%" />,
  bolt: <Bolt size="100%" />,
  font: <Type size="100%" />,
  analytics: <PieChart size="100%" />,
  mouse: <MousePointer2 size="100%" />,
  server: <Server size="100%" />,
  help: <HelpCircle size="100%" />,
  book: <BookOpen size="100%" />,
  search: <Search size="100%" />,
  chevronDown: <ChevronDown size="100%" />,
};
